### ISSUE TITLE
Can't resolve 'vue'

### ISSUE THREAD

**Issue by antonin-a** [abiodunjames/NodeJs-Todo-List#2] opened 2018-10-15 15:07 UTC
After almost half a day working on this I still didn't manage to make it work and having an issue with vue :/

```
sudo npm run build

 node-todo@0.1.1 build /home/cloud/todoapp
 webpack

Hash: d63f6c75366e6949b120
Version: webpack 3.12.0
Time: 1628ms
                   Asset    Size  Chunks             Chunk Names
./public/build/bundle.js  225 kB       0  [emitted]  main
  [15] ./public/src/main.js 282 bytes {0} [built]
    + 46 hidden modules

ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./public/src/components/CreateTodo.vue
Module not found: Error: Can't resolve './../bus.js' in '/home/cloud/todoapp/public/src/components'
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./public/src/components/CreateTodo.vue 15:0-30
 @ ./public/src/components/CreateTodo.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./public/src/components/App.vue
 @ ./public/src/components/App.vue
 @ ./public/src/main.js

ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./public/src/components/ListTodo.vue
Module not found: Error: Can't resolve './../bus.js' in '/home/cloud/todoapp/public/src/components'
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./public/src/components/ListTodo.vue 25:0-30
 @ ./public/src/components/ListTodo.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./public/src/components/App.vue
 @ ./public/src/components/App.vue
 @ ./public/src/main.js

ERROR in ./public/src/main.js
Module not found: Error: Can't resolve 'vue' in '/home/cloud/todoapp/public/src'
 @ ./public/src/main.js 4:0-22
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! node-todo@0.1.1 build: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the node-todo@0.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-15T15_05_35_236Z-debug.log

``` 

I saw you comment but https://github.com/vuejs-templates/webpack/issues/215 doesn't really help me. Do you have any idea ?

**Comment by shubhambattoo** [comment] 2019-02-17 08:54
Facing the same issue, was able to get past around this by putting the following in webpack.config.js

`  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js'
    }
  },`

but the vue components are not building just getting the static text inside index.html

**Comment by abiodunjames** [comment] 2019-04-16 06:36
You will need to download a standalone version of Vue to path `your/path/vue.js` and then reference it in `webpack.config.js`
```
alias: {
      vue: './vue.js'
    }
```
Early today, I'll be fixing this bug

**Comment by abiodunjames** [comment] 2019-04-19 10:07
I can't reproduce this issue you are having but I believe my comment earlier will fix this for you.

The runtime build is used by default when you ` import vue from 'vue' `; in your project. Template compiler is not available in the runtime build and hence the reason why you need to define an alias in `webpack.config.js`.

**Comment by abiodunjames** [comment] 2019-10-12 15:13
Fixed in https://github.com/abiodunjames/NodeJs-Todo-List/pull/3

**Closed by abiodunjames** 2019-10-12 15:13 UTC
